### ISSUE TITLE
Nullable float support in details view

### ISSUE THREAD

**Issue by ReDetection** [vas3k/GodMode2#1]
Great! I finally can define primary key other than `id` (blame apple, coredata), thanx! 

But I have a nullable float column, and when try to view details, I get this error message

```
builtins.TypeError
TypeError: type NoneType doesn't define __round__ method
```

Is there any easy fix?

**Comment by vas3k** [comment]
Try now

**Comment by ReDetection** [comment]
nope. made a pull request #2 with a similar fix — it was easy to copy-paste your change to one more place
