### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by oxozle** [vas3k/GodMode2#7]
Добрый день, появилось несколько вопросов

1. В предыдущей версии была поддержка MongoDB, а в этой нет, почему?
2. В итогах года 2012 (аж до туда дочитал) вы написали, что отказались от монги, можно узнать ваше мнение почему?

**Comment by vas3k** [comment]
Привет. 
1. Вторая версия была написана с нуля и в это время поддержка MongoDB была уже не нужна. 
2. В 2012-2014-м монга была исключительно глючным поделием и крешилась с сигфолтом каждую ночь, теряя все данные. Со временем всё стало получше, но тогда пришлось перейти на jsonb в постгресе. На них проект счастливо и стабильно прожил много лет пока не закрылся в этом году.

**Comment by oxozle** [comment]
Спасибо!
